// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	service "jezz-go-spotify-integration/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// ExecuteWithAuthentication provides a mock function with given fields: fn
func (_m *AuthService) ExecuteWithAuthentication(fn service.FnWithAuthentication) (interface{}, error) {
	ret := _m.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteWithAuthentication")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(service.FnWithAuthentication) (interface{}, error)); ok {
		return rf(fn)
	}
	if rf, ok := ret.Get(0).(func(service.FnWithAuthentication) interface{}); ok {
		r0 = rf(fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(service.FnWithAuthentication) error); ok {
		r1 = rf(fn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
