// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "jezz-go-spotify-integration/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// ExecuteWithAuthenticationFn is an autogenerated mock type for the ExecuteWithAuthenticationFn type
type ExecuteWithAuthenticationFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: accessToken
func (_m *ExecuteWithAuthenticationFn) Execute(accessToken model.AccessToken) (interface{}, error) {
	ret := _m.Called(accessToken)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(model.AccessToken) (interface{}, error)); ok {
		return rf(accessToken)
	}
	if rf, ok := ret.Get(0).(func(model.AccessToken) interface{}); ok {
		r0 = rf(accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(model.AccessToken) error); ok {
		r1 = rf(accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewExecuteWithAuthenticationFn creates a new instance of ExecuteWithAuthenticationFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecuteWithAuthenticationFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExecuteWithAuthenticationFn {
	mock := &ExecuteWithAuthenticationFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
