linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gofmt
    - goimports
    - ineffassign
    - typecheck
    - gocritic
    - misspell
    - revive
run:
  timeout: 5m

issues:
  exclude-dir:
    - mocks
