linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - goimports
run:
  timeout: 5m

issues:
  exclude-dirs:
    # Exclude any directory named 'mocks' regardless of its depth
    # This pattern is generally effective across OS (handles both / and \)
    - "^(.*/)?mocks(/.*)?$"

