// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "jezz-go-spotify-integration/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// HttpClient is an autogenerated mock type for the HttpClient type
type HttpClient struct {
	mock.Mock
}

// DoRequest provides a mock function with given fields: method, url, queryParams, accessToken, responseTypedOutput
func (_m *HttpClient) DoRequest(method model.HttpMethod, url string, queryParams *model.QueryParams, accessToken model.AccessToken, responseTypedOutput interface{}) error {
	ret := _m.Called(method, url, queryParams, accessToken, responseTypedOutput)

	if len(ret) == 0 {
		panic("no return value specified for DoRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.HttpMethod, string, *model.QueryParams, model.AccessToken, interface{}) error); ok {
		r0 = rf(method, url, queryParams, accessToken, responseTypedOutput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewHttpClient creates a new instance of HttpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHttpClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *HttpClient {
	mock := &HttpClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
