// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StringEvaluator is an autogenerated mock type for the StringEvaluator type
type StringEvaluator struct {
	mock.Mock
}

// String provides a mock function with no fields
func (_m *StringEvaluator) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewStringEvaluator creates a new instance of StringEvaluator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStringEvaluator(t interface {
	mock.TestingT
	Cleanup(func())
}) *StringEvaluator {
	mock := &StringEvaluator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
