// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "jezz-go-spotify-integration/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// AuthenticationFlow is an autogenerated mock type for the AuthenticationFlow type
type AuthenticationFlow struct {
	mock.Mock
}

// Authenticate provides a mock function with no fields
func (_m *AuthenticationFlow) Authenticate() (*model.Authentication, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *model.Authentication
	var r1 error
	if rf, ok := ret.Get(0).(func() (*model.Authentication, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *model.Authentication); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Authentication)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthenticationFlow creates a new instance of AuthenticationFlow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticationFlow(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticationFlow {
	mock := &AuthenticationFlow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
