# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI

on:
  workflow_call:
    inputs:
      go_version:
        description: 'The Go version to use for build and test'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go-project
        with:
          go-version: ${{ inputs.go_version }}

      - name: Lint
        run: make lint

      - name: Build
        run: make build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go-project
        with:
          go-version: ${{ inputs.go_version }}

      - name: Run Tests
        run: make test

      - name: Validate Test Coverage
        run: make test-coverage-detailed

      - name: Upload Test Coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./coverage_detailed.txt

      - name: Generate HTML Test Coverage
        run: make test-coverage-html

      - name: Upload HTML Test Coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: html-code-coverage-report
          path: ./coverage.html

      - name: Download Test Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report
          path: ./

      - name: Read Test Coverage Details
        id: read_coverage
        if: github.event_name == 'pull_request'
        run: |
          COVERAGE_CONTENT=$(cat coverage_detailed.txt)
          echo "coverage_details<<EOF" >> $GITHUB_OUTPUT
          echo "$COVERAGE_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post Test Coverage as PR Comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          header: "go-test-coverage"
          message: |
            ### 📊 Go Test Coverage Details
            <details>
            <summary>Click to view detailed coverage report</summary>
            
            ```
            ${{ steps.read_coverage.outputs.coverage_details }}
            ```
            
            </details>
            ---
            [View full HTML coverage report](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/html-code-coverage-report)

      - name: Clean up
        run: make clean
