# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI

on:
  workflow_call:
    inputs:
      go_version:
        description: 'The Go version to use for build and test'
        required: true
        type: string

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go Project
        uses: ./.github/actions/setup-go-project
        with:
          go-version: ${{ inputs.go_version }}

      - name: Lint
        run: make lint

      - name: Clean up
        run: make clean

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go Project
        uses: ./.github/actions/setup-go-project
        with:
          go-version: ${{ inputs.go_version }}

      - name: Build
        run: make build

      - name: Clean up
        run: make clean

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go Project
        uses: ./.github/actions/setup-go-project
        with:
          go-version: ${{ inputs.go_version }}

      - name: Run Tests
        run: make test

      - name: Clean up
        run: make clean

  test-coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go Project
        uses: ./.github/actions/setup-go-project
        with:
          go-version: ${{ inputs.go-version }}

      - name: Runs Test Coverage
        uses: ./.github/actions/test-coverage
        with:
          go_version: ${{ inputs.go_version }}
          run_id: ${{ github.run_id }}
          repository: ${{ github.repository }}
          server_url: ${{ github.server_url }}
          event_name: ${{ github.event_name }}
          min_coverage_percentage: '70'

      - name: Clean up
        run: make clean
