# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI - build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Pre-validation (CI) jobs: build, test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go-project
        with:
          go-version: '1.24'

      - name: Lint
        run: make lint

      - name: Build
        run: make build

  test:
    needs: build # This job will only run after the 'build' job successfully completes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go-project
        with:
          go-version: '1.24'

      - name: Run Tests
        run: make test

      - name: Validate Coverage
        run: make test-coverage

      - name: Clean up
        run: make clean