name: "PR Labeler"

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited  ]

jobs:
  add-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Insert labels
        uses: actions/labeler@v5