# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go PR to main

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  CI:
    uses: ./.github/workflows/go-ci.yml
    permissions:
      pull-requests: write
    with:
      go_version: '1.24'
