# https://github.com/marketplace/actions/labeler

name: "PR mgmt"

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited  ]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add PR labels
        uses: actions/labeler@v5